version: 2

jobs:
  test:
    working_directory: ~/fakelog
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - ~/.npm
            - ./node_modules
          key: cache-{{ checksum "package-lock.json" }}

      - run: npm run test

workflows:
  version: 2

  test:
    jobs:
      - test
